### ISSUE TITLE
I get an error when validating using a recursive JSON schema

### ISSUE THREAD

**Issue by starikovs** [jsonnext/codemirror-json-schema#131]
If I use this plugin to validate JSON in code mirror editor and pass a [recursive JSON schema](https://json-schema.org/understanding-json-schema/structuring#recursion) for validation:

```
    const state = EditorState.create({
      doc: JSON.stringify(object, null, 2),
      extensions: [jsonSchema(recursiveJSONSchema)],
    });

```

I get the following errors in console and validation stops working in the code mirror editor:

```
ERROR TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'properties' -> object with constructor 'Object'
    --- property 'drilldownColumn' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.compileSchema (index.js:30:37)
    at set rootSchema (index.js:31:41)
    at Draft04.setSchema (index.js:116:14)
    at new Draft (index.js:22:14)
    at new Draft04 (index.js:99:9)
    at JSONValidation.doValidation (json-validation.js:83:23)
    at json-validation.js:30:27
    at index.js:234:67
    at Array.map (<anonymous>)
```

**Comment by starikovs** [comment]
I'm closing it. The reason I got this error because I passed a derefferenced JSON schema. With regular JSON schema validation works as expected.
